# Lesson 05
## Линейные преобразования

In [1]:
import numpy as np

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$$
$$(-1-\lambda)(6-\lambda) - (-6)\cdot 2 = 0$$
$$\lambda^2 - 5\lambda + 6 = 0$$

$$\begin{cases}
     \lambda_1 = 2 \\
     \lambda_2 = 3
\end{cases}$$

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$$

$$\begin{cases}
    -x_1 -6x_2 = 2x_1 \\
    2x_1 + 6x_2 = 2x_2
\end{cases}$$

$$x_1 = -2x_2$$

$$x = \begin{pmatrix}
2\\ 
-1
\end{pmatrix}$$

$$\begin{cases}
    -x_1 -6x_2 = 3x_1 \\
    2x_1 + 6x_2 = 3x_2
\end{cases}$$

$$x_1 = -\frac{3}{2}x_2$$


$$x = \begin{pmatrix}
3\\ 
-2
\end{pmatrix}$$

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что любой вектор является для него собственным.

$$\begin{vmatrix}
-1-\lambda & -0\\ 
0 & -1-\lambda
\end{vmatrix} = 0$$
$$(-1-\lambda)(-1-\lambda) - 0 \cdot 0 = 0$$
$$(-1 - \lambda)^2 = 0$$

$$\begin{cases}
     \lambda_1 = -1 \\
     \lambda_2 = -1
\end{cases}$$

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$$

$$\begin{cases}
    -x_1 + 0 \cdot x_2 = -x_1 \\
    0 \cdot x_1 + (-x_2) = -x_2
\end{cases}$$


$$\begin{cases}
    x_1 - x_1 = 0 \\
    x_2 - x_2 = 0 
\end{cases}$$

$$\begin{cases}
    0 = 0 \\
    0 = 0 \\
\end{cases}$$


In [3]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


3. Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$$

$$\begin{cases}
    1 + 1 = \lambda \\
    -1 + 3 = \lambda
\end{cases}$$

$$\begin{cases}
    \lambda = 2 \\
    \lambda = 2 
\end{cases}\Rightarrow
\lambda=2$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2.$

4. Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix} 
3 \\
-3 \\
-4
\end{pmatrix} =
\lambda
\begin{pmatrix} 
3 \\
-3 \\
-4
\end{pmatrix}$$

$$\begin{cases}
    0 \cdot 3 + 3 \cdot (-3) + 0\cdot (-4) = 3 \lambda \\
    3 \cdot 3 + 0 \cdot (-3) + 0 \cdot (-4) = -3 \lambda \\
    0 \cdot (3) + 0 \cdot (-3) + 3 \cdot (-4) = -4 \lambda
\end{cases}$$

$$\begin{cases}
    -9 = 3 \lambda \\
    9 = -3 \lambda \\
    -12 = -4 \lambda
\end{cases}$$

$$\begin{cases}
    \lambda = -3 \\
    \lambda = -3 \\
    \lambda = 3 
\end{cases}$$

Такая система не имеет смысла. Таким образом, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.