# Lesson 08
## Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
V = W.T

In [5]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [6]:
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [7]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;

In [8]:
max(s)

8.824868854820448

$\left \| A \right \|_{E} = 8.82$

    б) норму Фробениуса.

$\left \| A \right \|_{F}=\sqrt{8.82^2 + 6.14 ^2 + 2.53^2} = 11.04$

In [9]:
s

array([8.82, 6.14, 2.53])

In [10]:
np.linalg.norm(s)

11.045361017187265

### Использование SVD

In [11]:
np.random.seed(42)
A = np.random.rand(30, 2)
A

array([[0.37, 0.95],
       [0.73, 0.6 ],
       [0.16, 0.16],
       [0.06, 0.87],
       [0.6 , 0.71],
       [0.02, 0.97],
       [0.83, 0.21],
       [0.18, 0.18],
       [0.3 , 0.52],
       [0.43, 0.29],
       [0.61, 0.14],
       [0.29, 0.37],
       [0.46, 0.79],
       [0.2 , 0.51],
       [0.59, 0.05],
       [0.61, 0.17],
       [0.07, 0.95],
       [0.97, 0.81],
       [0.3 , 0.1 ],
       [0.68, 0.44],
       [0.12, 0.5 ],
       [0.03, 0.91],
       [0.26, 0.66],
       [0.31, 0.52],
       [0.55, 0.18],
       [0.97, 0.78],
       [0.94, 0.89],
       [0.6 , 0.92],
       [0.09, 0.2 ],
       [0.05, 0.33]])

In [12]:
np.random.randn(30, 1)

array([[-1.48],
       [-0.72],
       [-0.46],
       [ 1.06],
       [ 0.34],
       [-1.76],
       [ 0.32],
       [-0.39],
       [-0.68],
       [ 0.61],
       [ 1.03],
       [ 0.93],
       [-0.84],
       [-0.31],
       [ 0.33],
       [ 0.98],
       [-0.48],
       [-0.19],
       [-1.11],
       [-1.2 ],
       [ 0.81],
       [ 1.36],
       [-0.07],
       [ 1.  ],
       [ 0.36],
       [-0.65],
       [ 0.36],
       [ 1.54],
       [-0.04],
       [ 1.56]])

In [13]:
z = np.array([(2 * A[:,0] - 5 * A[:,1])*np.random.randn(30,)]).T

In [14]:
M = np.hstack((A, z))
M

array([[ 0.37,  0.95, 10.49],
       [ 0.73,  0.6 , -1.26],
       [ 0.16,  0.16, -0.04],
       [ 0.06,  0.87,  1.26],
       [ 0.6 ,  0.71, -0.21],
       [ 0.02,  0.97,  9.56],
       [ 0.83,  0.21, -0.13],
       [ 0.18,  0.18, -0.2 ],
       [ 0.3 ,  0.52, -2.98],
       [ 0.43,  0.29,  0.31],
       [ 0.61,  0.14, -0.43],
       [ 0.29,  0.37,  0.63],
       [ 0.46,  0.79, -2.76],
       [ 0.2 ,  0.51, -0.71],
       [ 0.59,  0.05, -0.5 ],
       [ 0.61,  0.17,  0.19],
       [ 0.07,  0.95, -0.45],
       [ 0.97,  0.81, -2.04],
       [ 0.3 ,  0.1 , -0.08],
       [ 0.68,  0.44,  0.27],
       [ 0.12,  0.5 ,  0.88],
       [ 0.03,  0.91,  6.55],
       [ 0.26,  0.66, -0.83],
       [ 0.31,  0.52, -0.52],
       [ 0.55,  0.18,  0.  ],
       [ 0.97,  0.78,  0.45],
       [ 0.94,  0.89,  3.67],
       [ 0.6 ,  0.92,  1.44],
       [ 0.09,  0.2 ,  0.28],
       [ 0.05,  0.33,  1.23]])

In [15]:
S = np.cov(M.T)

In [16]:
U, s, W = np.linalg.svd(S)

In [17]:
s

array([9.33, 0.09, 0.07])

In [18]:
V = W.T
D = np.zeros_like(S, dtype=float)
D[np.diag_indices(min(S.shape))] = s

In [19]:
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[9.33 0.   0.  ]
 [0.   0.09 0.  ]
 [0.   0.   0.07]]
Матрица U:
[[-0.02 -0.8   0.6 ]
 [ 0.04 -0.61 -0.79]
 [ 1.    0.01  0.05]]
Матрица V:
[[-0.02 -0.8   0.6 ]
 [ 0.04 -0.61 -0.79]
 [ 1.    0.01  0.05]]


In [20]:
print(np.dot(np.dot(U, D), V.T))

[[ 0.09  0.   -0.22]
 [ 0.    0.1   0.41]
 [-0.22  0.41  9.3 ]]


In [21]:
U, s, W = np.linalg.svd(M)

In [22]:
V = W.T
D = np.zeros_like(M, dtype=float)
D[np.diag_indices(min(M.shape))] = s

In [23]:
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[17.07  0.    0.  ]
 [ 0.    3.79  0.  ]
 [ 0.    0.    1.43]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
Матрица U:
[[ 0.62 -0.05  0.1  -0.06 -0.12 -0.39 -0.17 -0.03  0.06 -0.1  -0.11 -0.09
   0.02 -0.01 -0.1  -0.14  0.01 -0.12 -0.06 -0.15 -0.06 -0.27 -0.02 -0.04
  -0.11 -0.22 -0.35 -0.18 -0.03 -0.06]
 [-0.07 -0.27  0.06  0.28 -0.04  0.38 -0.32 -0.02  0.02 -0.1  -0.24 -0.01
   0.04  0.08 -0.26 -0.22  0.29 -0.19 -0.11 -0.17  0.12  0.34  0.1   0.03
  -0.19 -0.1

In [24]:
print(np.dot(np.dot(U, D), V.T))

[[ 0.37  0.95 10.49]
 [ 0.73  0.6  -1.26]
 [ 0.16  0.16 -0.04]
 [ 0.06  0.87  1.26]
 [ 0.6   0.71 -0.21]
 [ 0.02  0.97  9.56]
 [ 0.83  0.21 -0.13]
 [ 0.18  0.18 -0.2 ]
 [ 0.3   0.52 -2.98]
 [ 0.43  0.29  0.31]
 [ 0.61  0.14 -0.43]
 [ 0.29  0.37  0.63]
 [ 0.46  0.79 -2.76]
 [ 0.2   0.51 -0.71]
 [ 0.59  0.05 -0.5 ]
 [ 0.61  0.17  0.19]
 [ 0.07  0.95 -0.45]
 [ 0.97  0.81 -2.04]
 [ 0.3   0.1  -0.08]
 [ 0.68  0.44  0.27]
 [ 0.12  0.5   0.88]
 [ 0.03  0.91  6.55]
 [ 0.26  0.66 -0.83]
 [ 0.31  0.52 -0.52]
 [ 0.55  0.18  0.  ]
 [ 0.97  0.78  0.45]
 [ 0.94  0.89  3.67]
 [ 0.6   0.92  1.44]
 [ 0.09  0.2   0.28]
 [ 0.05  0.33  1.23]]
